# Generated by Django 3.2.15 on 2022-08-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('baseStats', models.CharField(max_length=200)),
                ('height', models.IntegerField(max_length=100)),
                ('weight', models.IntegerField(max_length=100)),
                ('evolutions', models.CharField(max_length=250)),
            ],
        ),
    ]
