# Generated by Django 2.0.9 on 2022-08-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20220809_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='criature',
            name='id_c',
            field=models.IntegerField(default=0),
        ),
    ]
