# Generated by Django 2.0.9 on 2022-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_criature_id_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criature',
            name='baseStats',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='criature',
            name='evolutions',
            field=models.CharField(max_length=500),
        ),
    ]
