# Generated by Django 2.0.9 on 2022-08-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20220809_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criature',
            old_name='baseStats',
            new_name='evolution',
        ),
        migrations.RemoveField(
            model_name='criature',
            name='evolutions',
        ),
        migrations.RemoveField(
            model_name='criature',
            name='id_c',
        ),
        migrations.AddField(
            model_name='criature',
            name='base_stats',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='criature',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='criature',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criature',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
