# Generated by Django 2.0.9 on 2022-08-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20220810_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='criature',
            name='id_evolution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criature',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
